spring:
  application:
    name: reserva-sala
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reserva-sala}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    cors:
      allowed-origins: ${WEB_API:http://localhost:5173}
springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:true}